/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.controllerAdmin;
import javax.swing.JOptionPane;
import model.Admin;

/**
 *
 * @author gusta
 */
public class AdminViewLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminViewLogin
     */
    
        private Admin admin;
    
    public AdminViewLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        LoginAdm = new javax.swing.JLabel();
        usuarioLoginAdm = new javax.swing.JLabel();
        senhaLoginAdm = new javax.swing.JLabel();
        usuarioLoginTxtAdm = new javax.swing.JTextField();
        senhaLoginTxtAdm = new javax.swing.JTextField();
        loginButtonAdm = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        voltar_loginAdm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginPanel.setBackground(new java.awt.Color(0, 0, 0));

        LoginAdm.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        LoginAdm.setForeground(new java.awt.Color(0, 204, 0));
        LoginAdm.setText("LOGIN ADMINISTRADOR");

        usuarioLoginAdm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuarioLoginAdm.setForeground(new java.awt.Color(0, 204, 0));
        usuarioLoginAdm.setText("Usuário:");

        senhaLoginAdm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        senhaLoginAdm.setForeground(new java.awt.Color(0, 204, 0));
        senhaLoginAdm.setText("Senha:");

        usuarioLoginTxtAdm.setBackground(new java.awt.Color(102, 102, 102));
        usuarioLoginTxtAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioLoginTxtAdmActionPerformed(evt);
            }
        });

        senhaLoginTxtAdm.setBackground(new java.awt.Color(102, 102, 102));
        senhaLoginTxtAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaLoginTxtAdmActionPerformed(evt);
            }
        });

        loginButtonAdm.setBackground(new java.awt.Color(0, 0, 0));
        loginButtonAdm.setForeground(new java.awt.Color(0, 204, 0));
        loginButtonAdm.setText("Logar");
        loginButtonAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonAdmActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("<- Voltar para o cadastro");

        voltar_loginAdm.setBackground(new java.awt.Color(0, 0, 0));
        voltar_loginAdm.setForeground(new java.awt.Color(0, 204, 0));
        voltar_loginAdm.setText("Voltar");
        voltar_loginAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_loginAdmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(voltar_loginAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(senhaLoginAdm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(senhaLoginTxtAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(usuarioLoginAdm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(usuarioLoginTxtAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(LoginAdm)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginButtonAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(LoginAdm)
                .addGap(38, 38, 38)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioLoginAdm)
                    .addComponent(usuarioLoginTxtAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaLoginAdm)
                    .addComponent(senhaLoginTxtAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(loginButtonAdm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(voltar_loginAdm))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioLoginTxtAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioLoginTxtAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioLoginTxtAdmActionPerformed

    private void senhaLoginTxtAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaLoginTxtAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaLoginTxtAdmActionPerformed

    private void loginButtonAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonAdmActionPerformed
        // TODO add your handling code here:
         // 1. Obter valores dos campos
    String usuarioDigitado = usuarioLoginTxtAdm.getText().trim();
    String senhaDigitada = new String(senhaLoginTxtAdm.getText());
    
    // 2. Validação dos campos
    if (usuarioDigitado.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "O campo Usuário não pode estar vazio!", 
            "Erro", 
            JOptionPane.ERROR_MESSAGE);
        usuarioLoginTxtAdm.requestFocus();
        return;
    }

    if (senhaDigitada.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "O campo Senha não pode estar vazio!", 
            "Erro", 
            JOptionPane.ERROR_MESSAGE);
        senhaLoginTxtAdm.requestFocus();
        return;
    }
    
    // 3. Criar instância do controller
    controllerAdmin controller = new controllerAdmin();
    
    // 4. Tentar realizar o login
    Admin adminLogado = controller.logarAdministrador(usuarioDigitado, senhaDigitada);
    
    // 5. Verificar resultado
    if (adminLogado != null) {
        // Login bem-sucedido
        JOptionPane.showMessageDialog(this,
            "Login realizado com sucesso! Bem-vindo(a), " + adminLogado.getNome(),
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE);
        
        // Abrir menu principal do administrador
        new MenuAdmin().setVisible(true);
        this.dispose(); 
    } else {
        // Login falhou
        JOptionPane.showMessageDialog(this,
            "Usuário ou senha incorretos!",
            "Erro",
            JOptionPane.ERROR_MESSAGE);
        
        // Limpar campos e dar foco
        usuarioLoginTxtAdm.setText(""); 
        senhaLoginTxtAdm.setText("");   
        usuarioLoginTxtAdm.requestFocus(); 
    }

    }//GEN-LAST:event_loginButtonAdmActionPerformed

    private void voltar_loginAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_loginAdmActionPerformed
        // TODO add your handling code here:
        AdminViewCadastro telaAdminViewCadastro = new AdminViewCadastro();
        telaAdminViewCadastro.setLocationRelativeTo(null);
        telaAdminViewCadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltar_loginAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginAdm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton loginButtonAdm;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel senhaLoginAdm;
    private javax.swing.JTextField senhaLoginTxtAdm;
    private javax.swing.JLabel usuarioLoginAdm;
    private javax.swing.JTextField usuarioLoginTxtAdm;
    private javax.swing.JButton voltar_loginAdm;
    // End of variables declaration//GEN-END:variables
}
