/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Admin;
import dao.AdminDAO;
import Controller.controllerAdmin;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class AdminViewCadastro extends javax.swing.JFrame {

    /**
     * Creates new form AdminView
     */
    
    private Admin admin;
    
    public AdminViewCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cadastroPanel = new javax.swing.JPanel();
        senhaCadastroTxtAdm = new javax.swing.JTextField();
        cadastroButtonAdm = new javax.swing.JButton();
        CadastroAdm = new javax.swing.JLabel();
        nomeCadastroAdm = new javax.swing.JLabel();
        nomeCadastroTxtAdm = new javax.swing.JTextField();
        usuarioCadastroAdm = new javax.swing.JLabel();
        usuarioCadastroTxtAdm = new javax.swing.JTextField();
        senhaCadastroAdm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IrLoginAdm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        cadastroPanel.setBackground(new java.awt.Color(0, 0, 0));

        senhaCadastroTxtAdm.setBackground(new java.awt.Color(102, 102, 102));
        senhaCadastroTxtAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaCadastroTxtAdmActionPerformed(evt);
            }
        });

        cadastroButtonAdm.setBackground(new java.awt.Color(0, 0, 0));
        cadastroButtonAdm.setForeground(new java.awt.Color(0, 204, 0));
        cadastroButtonAdm.setText("Cadastrar");
        cadastroButtonAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroButtonAdmActionPerformed(evt);
            }
        });

        CadastroAdm.setBackground(new java.awt.Color(255, 255, 255));
        CadastroAdm.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        CadastroAdm.setForeground(new java.awt.Color(0, 204, 0));
        CadastroAdm.setText("CADASTRO ADMISTRADOR");

        nomeCadastroAdm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeCadastroAdm.setForeground(new java.awt.Color(0, 204, 0));
        nomeCadastroAdm.setText("Nome:");

        nomeCadastroTxtAdm.setBackground(new java.awt.Color(102, 102, 102));
        nomeCadastroTxtAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCadastroTxtAdmActionPerformed(evt);
            }
        });

        usuarioCadastroAdm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuarioCadastroAdm.setForeground(new java.awt.Color(0, 204, 0));
        usuarioCadastroAdm.setText("Usuário:");

        usuarioCadastroTxtAdm.setBackground(new java.awt.Color(102, 102, 102));
        usuarioCadastroTxtAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioCadastroTxtAdmActionPerformed(evt);
            }
        });

        senhaCadastroAdm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        senhaCadastroAdm.setForeground(new java.awt.Color(0, 204, 0));
        senhaCadastroAdm.setText("Senha:");

        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Ir para LOGIN ->");

        IrLoginAdm.setBackground(new java.awt.Color(0, 0, 0));
        IrLoginAdm.setForeground(new java.awt.Color(0, 204, 0));
        IrLoginAdm.setText("Login");
        IrLoginAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrLoginAdmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroPanelLayout = new javax.swing.GroupLayout(cadastroPanel);
        cadastroPanel.setLayout(cadastroPanelLayout);
        cadastroPanelLayout.setHorizontalGroup(
            cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPanelLayout.createSequentialGroup()
                .addGap(0, 313, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(IrLoginAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CadastroAdm)
                .addGap(67, 67, 67))
            .addGroup(cadastroPanelLayout.createSequentialGroup()
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroPanelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(cadastroPanelLayout.createSequentialGroup()
                                        .addComponent(usuarioCadastroAdm)
                                        .addGap(25, 25, 25)
                                        .addComponent(usuarioCadastroTxtAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cadastroPanelLayout.createSequentialGroup()
                                        .addComponent(nomeCadastroAdm)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nomeCadastroTxtAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroPanelLayout.createSequentialGroup()
                                .addComponent(senhaCadastroAdm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(senhaCadastroTxtAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(cadastroPanelLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(cadastroButtonAdm)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cadastroPanelLayout.setVerticalGroup(
            cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(CadastroAdm)
                .addGap(54, 54, 54)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCadastroAdm)
                    .addComponent(nomeCadastroTxtAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioCadastroAdm)
                    .addComponent(usuarioCadastroTxtAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaCadastroAdm)
                    .addComponent(senhaCadastroTxtAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cadastroButtonAdm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IrLoginAdm))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cadastroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadastroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senhaCadastroTxtAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaCadastroTxtAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaCadastroTxtAdmActionPerformed

    private void cadastroButtonAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroButtonAdmActionPerformed

// 1. Obter valores dos campos
   // Obter valores dos campos
    String nome = nomeCadastroTxtAdm.getText().trim();
    String usuario = usuarioCadastroTxtAdm.getText().trim();
    String senha = new String(senhaCadastroTxtAdm.getText()).trim();

    // 2. Validação dos campos
    if (nome.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "O campo Nome não pode estar vazio!", 
            "Erro", 
            JOptionPane.ERROR_MESSAGE);
        nomeCadastroTxtAdm.requestFocus();
        return;
    }

    if (usuario.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "O campo Usuário não pode estar vazio!", 
            "Erro", 
            JOptionPane.ERROR_MESSAGE);
        usuarioCadastroTxtAdm.requestFocus();
        return;
    }

    if (senha.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "O campo Senha não pode estar vazio!", 
            "Erro", 
            JOptionPane.ERROR_MESSAGE);
        senhaCadastroTxtAdm.requestFocus();
        return;
    }

    // 3. Criar objeto Admin (model)
    Admin adm = new Admin();
    adm.setNome(nome);
    adm.setUsuario(usuario);
    adm.setSenha(senha); // Considerar adicionar criptografia aqui

    try {
        // 4. Chamar controller para cadastrar
        controllerAdmin controller = new controllerAdmin();
        controller.cadastrarAdministrador(adm);

        // 5. Limpar campos após cadastro
        nomeCadastroTxtAdm.setText("");
        usuarioCadastroTxtAdm.setText("");
        senhaCadastroTxtAdm.setText("");

        // 6. Feedback de sucesso
        JOptionPane.showMessageDialog(this, 
            "Administrador cadastrado com sucesso!", 
            "Sucesso", 
            JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Erro ao cadastrar administrador: " + e.getMessage(), 
            "Erro", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }



        

    }//GEN-LAST:event_cadastroButtonAdmActionPerformed

    private void nomeCadastroTxtAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCadastroTxtAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCadastroTxtAdmActionPerformed

    private void usuarioCadastroTxtAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioCadastroTxtAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioCadastroTxtAdmActionPerformed

    private void IrLoginAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrLoginAdmActionPerformed
        // TODO add your handling code here:
        AdminViewLogin telaAdminViewLogin = new AdminViewLogin();
        telaAdminViewLogin.setLocationRelativeTo(null);
        telaAdminViewLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IrLoginAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadastroAdm;
    private javax.swing.JButton IrLoginAdm;
    private javax.swing.JButton cadastroButtonAdm;
    private javax.swing.JPanel cadastroPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeCadastroAdm;
    private javax.swing.JTextField nomeCadastroTxtAdm;
    private javax.swing.JLabel senhaCadastroAdm;
    private javax.swing.JTextField senhaCadastroTxtAdm;
    private javax.swing.JLabel usuarioCadastroAdm;
    private javax.swing.JTextField usuarioCadastroTxtAdm;
    // End of variables declaration//GEN-END:variables
}
