/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.UsuarioDAO;
import javax.swing.JOptionPane;
import model.Usuario;
import Controller.controllerUsuario;



/**
 *
 * @author gusta
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    private Usuario usuario;
    
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroPanel = new javax.swing.JPanel();
        senhaCadastroTxt = new javax.swing.JTextField();
        cadastroButton = new javax.swing.JButton();
        Cadastro = new javax.swing.JLabel();
        nomeCadastro = new javax.swing.JLabel();
        nomeCadastroTxt = new javax.swing.JTextField();
        usuarioCadastro = new javax.swing.JLabel();
        usuarioCadastroTxt = new javax.swing.JTextField();
        senhaCadastro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonAcessAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 0));

        cadastroPanel.setBackground(new java.awt.Color(0, 0, 0));

        senhaCadastroTxt.setBackground(new java.awt.Color(102, 102, 102));
        senhaCadastroTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaCadastroTxtActionPerformed(evt);
            }
        });

        cadastroButton.setBackground(new java.awt.Color(0, 0, 0));
        cadastroButton.setForeground(new java.awt.Color(0, 204, 0));
        cadastroButton.setText("Cadastrar");
        cadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroButtonActionPerformed(evt);
            }
        });

        Cadastro.setBackground(new java.awt.Color(255, 255, 255));
        Cadastro.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Cadastro.setForeground(new java.awt.Color(0, 204, 0));
        Cadastro.setText("CADASTRO");

        nomeCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeCadastro.setForeground(new java.awt.Color(0, 204, 0));
        nomeCadastro.setText("Nome:");

        nomeCadastroTxt.setBackground(new java.awt.Color(102, 102, 102));
        nomeCadastroTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCadastroTxtActionPerformed(evt);
            }
        });

        usuarioCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuarioCadastro.setForeground(new java.awt.Color(0, 204, 0));
        usuarioCadastro.setText("Usuário:");

        usuarioCadastroTxt.setBackground(new java.awt.Color(102, 102, 102));
        usuarioCadastroTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioCadastroTxtActionPerformed(evt);
            }
        });

        senhaCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        senhaCadastro.setForeground(new java.awt.Color(0, 204, 0));
        senhaCadastro.setText("Senha:");

        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Ir para LOGIN ->");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(0, 204, 0));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonAcessAdmin.setText("Admin acess");
        jButtonAcessAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroPanelLayout = new javax.swing.GroupLayout(cadastroPanel);
        cadastroPanel.setLayout(cadastroPanelLayout);
        cadastroPanelLayout.setHorizontalGroup(
            cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPanelLayout.createSequentialGroup()
                        .addComponent(jButtonAcessAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cadastroButton)
                        .addGap(152, 152, 152))))
            .addGroup(cadastroPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(cadastroPanelLayout.createSequentialGroup()
                                .addComponent(usuarioCadastro)
                                .addGap(25, 25, 25)
                                .addComponent(usuarioCadastroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPanelLayout.createSequentialGroup()
                                .addComponent(nomeCadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cadastro)
                                    .addComponent(nomeCadastroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroPanelLayout.createSequentialGroup()
                        .addComponent(senhaCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(senhaCadastroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        cadastroPanelLayout.setVerticalGroup(
            cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Cadastro)
                .addGap(75, 75, 75)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCadastro)
                    .addComponent(nomeCadastroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioCadastro)
                    .addComponent(usuarioCadastroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaCadastro)
                    .addComponent(senhaCadastroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(cadastroButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButtonAcessAdmin))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastroPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeCadastroTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCadastroTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCadastroTxtActionPerformed

    private void usuarioCadastroTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioCadastroTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioCadastroTxtActionPerformed

    private void senhaCadastroTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaCadastroTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaCadastroTxtActionPerformed

    private void cadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroButtonActionPerformed
        // TODO add your handling code here:
        
        String nome = nomeCadastroTxt.getText().trim();
        String usuario = usuarioCadastroTxt.getText().trim();
        String senha = senhaCadastroTxt.getText().trim();

        // Validação dos campos
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo Nome não pode estar vazio!", "Erro", JOptionPane.ERROR_MESSAGE);
                nomeCadastroTxt.requestFocus(); 
                    return; 
        }

        if (usuario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo Usuário não pode estar vazio!", "Erro", JOptionPane.ERROR_MESSAGE);
                usuarioCadastroTxt.requestFocus();
                    return;
        }

        if (senha.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo Senha não pode estar vazio!", "Erro", JOptionPane.ERROR_MESSAGE);
                senhaCadastroTxt.requestFocus();
                return;
        }

        
        Usuario usu = new Usuario();
        usu.setNome(nome);
        usu.setUsuario(usuario);
        usu.setSenha(senha);


        controllerUsuario controllerUsuario = new controllerUsuario();
        controllerUsuario.cadastrarUsuario(usu); // Método deve existir no UsuarioDAO

// Limpa os campos após o cadastro
        nomeCadastroTxt.setText("");
        usuarioCadastroTxt.setText("");
        senhaCadastroTxt.setText("");

// Exibe mensagem de sucesso
JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
                                                      
    }//GEN-LAST:event_cadastroButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login telaLogin = new Login();
        telaLogin.setLocationRelativeTo(null); 
        telaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAcessAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessAdminActionPerformed
        // TODO add your handling code here:
        AdminViewCadastro telaAdminViewCadastro = new AdminViewCadastro();
        telaAdminViewCadastro.setLocationRelativeTo(null);
        telaAdminViewCadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAcessAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cadastro;
    private javax.swing.JButton cadastroButton;
    private javax.swing.JPanel cadastroPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAcessAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nomeCadastro;
    private javax.swing.JTextField nomeCadastroTxt;
    private javax.swing.JLabel senhaCadastro;
    private javax.swing.JTextField senhaCadastroTxt;
    private javax.swing.JLabel usuarioCadastro;
    private javax.swing.JTextField usuarioCadastroTxt;
    // End of variables declaration//GEN-END:variables
}
