/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.UsuarioDAO;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author gusta
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    private Usuario usuario;
    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        usuarioLogin = new javax.swing.JLabel();
        senhaLogin = new javax.swing.JLabel();
        usuarioLoginTxt = new javax.swing.JTextField();
        senhaLoginTxt = new javax.swing.JTextField();
        loginButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        voltar_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginPanel.setBackground(new java.awt.Color(0, 0, 0));

        Login.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Login.setForeground(new java.awt.Color(0, 204, 0));
        Login.setText("LOGIN");

        usuarioLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuarioLogin.setForeground(new java.awt.Color(0, 204, 0));
        usuarioLogin.setText("Usuário:");

        senhaLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        senhaLogin.setForeground(new java.awt.Color(0, 204, 0));
        senhaLogin.setText("Senha:");

        usuarioLoginTxt.setBackground(new java.awt.Color(102, 102, 102));
        usuarioLoginTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioLoginTxtActionPerformed(evt);
            }
        });

        senhaLoginTxt.setBackground(new java.awt.Color(102, 102, 102));
        senhaLoginTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaLoginTxtActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(0, 0, 0));
        loginButton.setForeground(new java.awt.Color(0, 204, 0));
        loginButton.setText("Logar");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("<- Voltar para o cadastro");

        voltar_login.setBackground(new java.awt.Color(0, 0, 0));
        voltar_login.setForeground(new java.awt.Color(0, 204, 0));
        voltar_login.setText("Voltar");
        voltar_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senhaLogin)
                            .addComponent(usuarioLogin))
                        .addGap(18, 18, 18)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usuarioLoginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhaLoginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(Login))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(voltar_login, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Login)
                .addGap(37, 37, 37)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioLogin)
                    .addComponent(usuarioLoginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaLogin)
                    .addComponent(senhaLoginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(loginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(voltar_login))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioLoginTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioLoginTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioLoginTxtActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String usuarioDigita = usuarioLoginTxt.getText().trim();
        String senhaDigita = new String(senhaLoginTxt.getText());
        
        if (usuarioDigita.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo Usuário não pode estar vazio!", "Erro", JOptionPane.ERROR_MESSAGE);
                usuarioLoginTxt.requestFocus();
                    return;
        }

        if (senhaDigita.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo Senha não pode estar vazio!", "Erro", JOptionPane.ERROR_MESSAGE);
                senhaLoginTxt.requestFocus();
                return;
        }
        
        // Usa a UsuarioDAO para verificar
    UsuarioDAO usuarioDAO = new UsuarioDAO();
    Usuario usuarioLogado = usuarioDAO.logarUsuario(usuarioDigita, senhaDigita);
    
    // Verifica se o login foi bem-sucedido
    if (usuarioLogado != null) {
        JOptionPane.showMessageDialog(this,
            "Login realizado com sucesso! Bem-vindo(a), " + usuarioLogado.getNome(),
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE);

        new Menu().setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this,
            "Usuário ou senha incorretos!",
            "Erro",
            JOptionPane.ERROR_MESSAGE);

        usuarioLoginTxt.setText("");
        senhaLoginTxt.setText("");
        usuarioLoginTxt.requestFocus();
    }
        
        
        
        
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void voltar_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_loginActionPerformed
        // TODO add your handling code here:
        Cadastro telaCadastro = new Cadastro();
        telaCadastro.setLocationRelativeTo(null); // Centraliza na tela
        telaCadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltar_loginActionPerformed

    private void senhaLoginTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaLoginTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaLoginTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel senhaLogin;
    private javax.swing.JTextField senhaLoginTxt;
    private javax.swing.JLabel usuarioLogin;
    private javax.swing.JTextField usuarioLoginTxt;
    private javax.swing.JButton voltar_login;
    // End of variables declaration//GEN-END:variables
}
