/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.controllerUsuario;
import dao.UsuarioDAO;
import javax.swing.JOptionPane;
import model.Usuario;


/**
 *
 * @author gusta
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    private Usuario usuario;
    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        usuarioLogin = new javax.swing.JLabel();
        senhaLogin = new javax.swing.JLabel();
        usuarioLoginTxt = new javax.swing.JTextField();
        senhaLoginTxt = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        voltar_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabelLogin.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(0, 204, 0));
        jLabelLogin.setText("LOGIN");

        usuarioLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuarioLogin.setForeground(new java.awt.Color(0, 204, 0));
        usuarioLogin.setText("Usuario:");

        senhaLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        senhaLogin.setForeground(new java.awt.Color(0, 204, 0));
        senhaLogin.setText("Senha:");

        usuarioLoginTxt.setBackground(new java.awt.Color(102, 102, 102));
        usuarioLoginTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioLoginTxtActionPerformed(evt);
            }
        });

        senhaLoginTxt.setBackground(new java.awt.Color(102, 102, 102));
        senhaLoginTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaLoginTxtActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(0, 0, 0));
        loginButton.setForeground(new java.awt.Color(0, 204, 0));
        loginButton.setText("Logar");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        voltar_login.setBackground(new java.awt.Color(0, 0, 0));
        voltar_login.setForeground(new java.awt.Color(0, 204, 0));
        voltar_login.setText("Voltar");
        voltar_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_loginActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("<- - Voltar para o Cadastro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senhaLogin)
                            .addComponent(usuarioLogin))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuarioLoginTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(senhaLoginTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(voltar_login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(loginButton)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelLogin)
                        .addGap(143, 143, 143))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelLogin)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioLogin)
                    .addComponent(usuarioLoginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(senhaLogin)
                    .addComponent(senhaLoginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(loginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltar_login)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        
        String usuarioDigita = usuarioLoginTxt.getText().trim();
        String senhaDigita = new String(senhaLoginTxt.getText());
        
        if (usuarioDigita.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo Usuário não pode estar vazio!", "Erro", JOptionPane.ERROR_MESSAGE);
                usuarioLoginTxt.requestFocus();
                    return;
        }

        if (senhaDigita.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo Senha não pode estar vazio!", "Erro", JOptionPane.ERROR_MESSAGE);
                senhaLoginTxt.requestFocus();
                return;
        }
        
      
    controllerUsuario controllerUsuario = new controllerUsuario();

        // Tenta realizar o login usando o ControllerUsuario
        Usuario usuarioLogado = controllerUsuario.logarUsuario(usuarioDigita, senhaDigita);

        
        if (usuarioLogado != null) {
            
            JOptionPane.showMessageDialog(this,
                "Login realizado com sucesso! Bem-vindo(a), " + usuarioLogado.getNome(),
                     "Sucesso",
                     JOptionPane.INFORMATION_MESSAGE);

            new Menu().setVisible(true);
            this.dispose(); 
            } else {
                
                   JOptionPane.showMessageDialog(this,
                     "Usuário ou senha incorretos!",
                     "Erro",
                     JOptionPane.ERROR_MESSAGE);

    usuarioLoginTxt.setText(""); 
    senhaLoginTxt.setText("");   
    usuarioLoginTxt.requestFocus(); 
        
        }   
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void voltar_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_loginActionPerformed
        // TODO add your handling code here:
        Cadastro telaCadastro = new Cadastro();
        telaCadastro.setLocationRelativeTo(null); // Centraliza na tela
        telaCadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltar_loginActionPerformed

    private void senhaLoginTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaLoginTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaLoginTxtActionPerformed

    private void usuarioLoginTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioLoginTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioLoginTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel senhaLogin;
    private javax.swing.JTextField senhaLoginTxt;
    private javax.swing.JLabel usuarioLogin;
    private javax.swing.JTextField usuarioLoginTxt;
    private javax.swing.JButton voltar_login;
    // End of variables declaration//GEN-END:variables
}
