/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author felip
 */
// Tela de menu
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMenu = new javax.swing.JLabel();
        bt_Suasplaylists = new javax.swing.JButton();
        bt_Musicas = new javax.swing.JButton();
        bt_criaPlaylist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabelMenu.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabelMenu.setForeground(new java.awt.Color(51, 255, 51));
        jLabelMenu.setText("SpotiFEI");

        bt_Suasplaylists.setBackground(new java.awt.Color(0, 0, 0));
        bt_Suasplaylists.setForeground(new java.awt.Color(51, 255, 51));
        bt_Suasplaylists.setText("Suas Playlists");
        bt_Suasplaylists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SuasplaylistsActionPerformed(evt);
            }
        });

        bt_Musicas.setBackground(new java.awt.Color(0, 0, 0));
        bt_Musicas.setForeground(new java.awt.Color(51, 255, 51));
        bt_Musicas.setText("Músicas");
        bt_Musicas.setActionCommand("");
        bt_Musicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_MusicasActionPerformed(evt);
            }
        });

        bt_criaPlaylist.setBackground(new java.awt.Color(0, 0, 0));
        bt_criaPlaylist.setForeground(new java.awt.Color(51, 255, 51));
        bt_criaPlaylist.setText("Crie uma Playlist");
        bt_criaPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_criaPlaylistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_Suasplaylists, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_criaPlaylist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(bt_Musicas, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelMenu)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Suasplaylists, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_criaPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Musicas, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_SuasplaylistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SuasplaylistsActionPerformed
        PlayList telaPlaylist = new PlayList();
    // Centraliza a nova janela na tela
    telaPlaylist.setLocationRelativeTo(null);
    // Exibe a tela de playlist
    telaPlaylist.setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_bt_SuasplaylistsActionPerformed

    private void bt_criaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_criaPlaylistActionPerformed
        CriaPlaylist telaCriaPlaylist = new CriaPlaylist();
    telaCriaPlaylist.setLocationRelativeTo(null); // Centraliza na tela
    telaCriaPlaylist.setVisible(true);
    this.dispose(); // Fecha a tela atual// TODO add your handling code here:
    }//GEN-LAST:event_bt_criaPlaylistActionPerformed

    private void bt_MusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_MusicasActionPerformed
       TelaMusica telaMusica = new TelaMusica();
    telaMusica.setLocationRelativeTo(null);  // Centraliza a janela
    telaMusica.setVisible(true);             // Torna a janela visível
    this.dispose();         // TODO add your handling code here: // TODO add your handling code here:
    }//GEN-LAST:event_bt_MusicasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Musicas;
    private javax.swing.JButton bt_Suasplaylists;
    private javax.swing.JButton bt_criaPlaylist;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
