/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author gusta
 */
public class Musica extends javax.swing.JFrame {

    /**
     * Creates new form Musica
     */
    public Musica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        musicaPanel = new javax.swing.JPanel();
        musicaLabel = new javax.swing.JLabel();
        bt_irMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        telaDasMusicas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        musicaPanel.setBackground(new java.awt.Color(0, 0, 0));

        musicaLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        musicaLabel.setForeground(new java.awt.Color(0, 255, 51));
        musicaLabel.setText("MÚSICAS");

        bt_irMenu.setBackground(new java.awt.Color(0, 0, 0));
        bt_irMenu.setForeground(new java.awt.Color(51, 255, 51));
        bt_irMenu.setText("Menu");
        bt_irMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_irMenuActionPerformed(evt);
            }
        });

        telaDasMusicas.setColumns(20);
        telaDasMusicas.setRows(5);
        jScrollPane1.setViewportView(telaDasMusicas);

        javax.swing.GroupLayout musicaPanelLayout = new javax.swing.GroupLayout(musicaPanel);
        musicaPanel.setLayout(musicaPanelLayout);
        musicaPanelLayout.setHorizontalGroup(
            musicaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, musicaPanelLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(musicaLabel)
                .addGap(133, 133, 133))
            .addGroup(musicaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(musicaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(musicaPanelLayout.createSequentialGroup()
                        .addComponent(bt_irMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        musicaPanelLayout.setVerticalGroup(
            musicaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicaPanelLayout.createSequentialGroup()
                .addComponent(musicaLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bt_irMenu)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(musicaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(musicaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_irMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_irMenuActionPerformed
        // TODO add your handling code here:
        Menu telaMenu = new Menu();
        telaMenu.setLocationRelativeTo(null);
        telaMenu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_bt_irMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Musica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Musica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Musica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Musica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Musica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_irMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel musicaLabel;
    private javax.swing.JPanel musicaPanel;
    private javax.swing.JTextArea telaDasMusicas;
    // End of variables declaration//GEN-END:variables
}
