/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.controllerMusica;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Musica;

/**
 *
 * @author gusta
 */
// Tela da Musica

public class TelaMusica extends javax.swing.JFrame {
    
    private controllerMusica controller;
    
        /**
     * Creates new form TelaMusica
     */
    public TelaMusica() {
        initComponents();
        this.controller = new controllerMusica();
        configurarTabela();
        carregarMusicas();
    }
    
    private void configurarTabela() {
        DefaultTableModel model = new DefaultTableModel(
            new Object[][]{},
            new String[]{"Título", "Artista", "Gênero"}
        );
        jTableMusicas.setModel(model);
    }
    
    private void carregarMusicas() {
        DefaultTableModel model = (DefaultTableModel) jTableMusicas.getModel();
        model.setRowCount(0);
    
        List<Musica> musicas = controller.listarTodasMusicas();
        for (Musica musica : musicas) {
            model.addRow(new Object[]{
                musica.getTitulo(),
                musica.getArtista(),
                musica.getGenero()
            });
        }
    }
    
        
    
    
    
       
    
       
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMusica = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMusicas = new javax.swing.JTable();
        jTextFieldBusca = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabelMusicas = new javax.swing.JLabel();
        botaoMenu = new javax.swing.JButton();
        BotaoPL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMusica.setBackground(new java.awt.Color(0, 0, 0));

        jTableMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMusicas);

        jButtonBuscar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBuscar.setForeground(new java.awt.Color(0, 204, 0));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabelMusicas.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabelMusicas.setForeground(new java.awt.Color(0, 204, 0));
        jLabelMusicas.setText("MUSICA");

        botaoMenu.setText("Menu");
        botaoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuActionPerformed(evt);
            }
        });

        BotaoPL.setText("Suas Playlists");
        BotaoPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMusicaLayout = new javax.swing.GroupLayout(jPanelMusica);
        jPanelMusica.setLayout(jPanelMusicaLayout);
        jPanelMusicaLayout.setHorizontalGroup(
            jPanelMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMusicaLayout.createSequentialGroup()
                .addGroup(jPanelMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMusicaLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMusicaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBuscar))
                            .addGroup(jPanelMusicaLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(botaoMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(BotaoPL))))
                    .addGroup(jPanelMusicaLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabelMusicas, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanelMusicaLayout.setVerticalGroup(
            jPanelMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMusicaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelMusicas)
                .addGap(18, 18, 18)
                .addGroup(jPanelMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelMusicaLayout.createSequentialGroup()
                        .addGroup(jPanelMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoMenu)
                            .addComponent(BotaoPL)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMusica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableMusicas.getModel();
        model.setRowCount(0);
        
        List<Musica> resultados = controller.buscarMusicas(jTextFieldBusca.getText());
        for (Musica musica : resultados) {
            model.addRow(new Object[]{
                musica.getTitulo(),
                musica.getArtista(),
                musica.getGenero()
            });
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void botaoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuActionPerformed
        // TODO add your handling code here:
        Menu telaMenu = new Menu();
        telaMenu.setLocationRelativeTo(null); // Centraliza na tela
        telaMenu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_botaoMenuActionPerformed

    private void BotaoPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPLActionPerformed
        // TODO add your handling code here:
        PlayList telaPlaylist = new PlayList();   
        telaPlaylist.setLocationRelativeTo(null);
        telaPlaylist.setVisible(true);   
        this.dispose();
    }//GEN-LAST:event_BotaoPLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMusica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoPL;
    private javax.swing.JButton botaoMenu;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabelMusicas;
    private javax.swing.JPanel jPanelMusica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMusicas;
    private javax.swing.JTextField jTextFieldBusca;
    // End of variables declaration//GEN-END:variables
}
